In [67]:
import pandas as pd

In [68]:
df = pd.read_csv(
    'mabel.txt',
    header=None,
    on_bad_lines='skip',
    encoding='utf8'
)

In [69]:
df

           0                                                  1
0   05/12/19   1:42 pm - Messages to this chat and calls are...
1   05/12/19   1:42 pm - Mabel Infoziant: Hi this is Mabel w...
2   05/12/19   1:42 pm - Mabel Infoziant: What’s your full name
3   05/12/19                      1:42 pm - AR❤: Ramisha Rani K
4   05/12/19                      1:42 pm - Mabel Infoziant: Ok
5   05/12/19   1:42 pm - Mabel Infoziant: ramisharanik@gmail...
6   05/12/19          1:43 pm - Mabel Infoziant: Your email Id?
7   05/12/19                             1:43 pm - AR❤: Yes Mam
8   05/12/19   1:43 pm - Mabel Infoziant: I will send 2 abst...
9   05/12/19                            1:43 pm - AR❤: Yeah mam
10  05/12/19   1:43 pm - Mabel Infoziant: Give me the list t...
11  05/12/19   1:43 pm - Mabel Infoziant: Send me cbe office...
12  05/12/19   1:44 pm - AR❤: Yeah Mam within Evening I will...
13  05/12/19   1:45 pm - AR❤: Tomorrow I have to visit the o...
14  05/12/19                      1:48 pm - Mabel Infoziant: ok
15  05/12/19   1:48 pm - Mabel Infoziant: send the details o...
16  05/12/19   1:49 pm - AR❤: Sure mam. Soon I will share de...
17  05/12/19   2:00 pm - AR❤: I have read the Abstract mam. ...
18  05/12/19   2:04 pm - Mabel Infoziant: I think Vignesh ha...
19  05/12/19   2:04 pm - Mabel Infoziant: I have sent the ab...
20  05/12/19                              2:06 pm - AR❤: Ok mam
21  05/12/19   2:07 pm - AR❤: I have read both the abstract ...
22  05/12/19   4:44 pm - Mabel Infoziant: Yes we need to ya ...
23  05/12/19                           4:48 pm - AR❤: Sure mam.
24  05/12/19                   8:07 pm - AR❤: Shall I call mam?
25  08/12/19   10:45 pm - Mabel Infoziant: Hi I was at churc...
26  08/12/19                         11:52 pm - AR❤: It's k mam
27  08/12/19   11:55 pm - AR❤: Just to know the tomorrow pla...
28  09/12/19    12:09 pm - AR❤: Mam can u send Vignesh number??
29  09/12/19   12:13 pm - Mabel Infoziant: Vignesh ML Infozi...
30  09/12/19   12:23 pm - Mabel Infoziant: I was in a meetin...
31  09/12/19                    12:25 pm - AR❤: Can I cal u mam
32  09/12/19   12:26 pm - AR❤: Waiting for u r finalization ...
33  09/12/19   12:26 pm - AR❤: If we finiliaze I can work wi...
34  09/12/19   12:28 pm - AR❤: So what ever may be ..if you ...
35  09/12/19           12:28 pm - AR❤: You deleted this message
36  09/12/19                     12:29 pm - AR❤: Do the needful
37  09/12/19   12:41 pm - Mabel Infoziant: No ma please hold...
38  09/12/19                     12:42 pm - AR❤: Ok mam thank u
39  10/12/19   7:59 am - Mabel Infoziant: Ramisha we need to...
40  10/12/19   8:00 am - Mabel Infoziant: Be ready to discus...
41  10/12/19                            8:55 am - AR❤: Okay mam
42  12/12/19                      2:26 pm - Mabel Infoziant: ok
43  15/12/19                     8:22 pm - AR❤: Mam are u free?
44  15/12/19   8:40 pm - Mabel Infoziant: Am at church can c...
45  15/12/19   8:40 pm - AR❤: Kk mam. I will ask Arun brothe...
46  18/12/19                              3:09 pm - AR❤: Hi mam
47  18/12/19                    3:09 pm - AR❤: Any updates mam?
48  18/12/19   3:11 pm - Mabel Infoziant: U might have to st...
49  18/12/19   3:11 pm - Mabel Infoziant: There is one proje...
50  18/12/19                            3:12 pm - AR❤: Kk mam👍🏻

In [70]:
df=df.drop(0)

In [71]:
df.columns=['Date','Chat']
df

        Date                                               Chat
1   05/12/19   1:42 pm - Mabel Infoziant: Hi this is Mabel w...
2   05/12/19   1:42 pm - Mabel Infoziant: What’s your full name
3   05/12/19                      1:42 pm - AR❤: Ramisha Rani K
4   05/12/19                      1:42 pm - Mabel Infoziant: Ok
5   05/12/19   1:42 pm - Mabel Infoziant: ramisharanik@gmail...
6   05/12/19          1:43 pm - Mabel Infoziant: Your email Id?
7   05/12/19                             1:43 pm - AR❤: Yes Mam
8   05/12/19   1:43 pm - Mabel Infoziant: I will send 2 abst...
9   05/12/19                            1:43 pm - AR❤: Yeah mam
10  05/12/19   1:43 pm - Mabel Infoziant: Give me the list t...
11  05/12/19   1:43 pm - Mabel Infoziant: Send me cbe office...
12  05/12/19   1:44 pm - AR❤: Yeah Mam within Evening I will...
13  05/12/19   1:45 pm - AR❤: Tomorrow I have to visit the o...
14  05/12/19                      1:48 pm - Mabel Infoziant: ok
15  05/12/19   1:48 pm - Mabel Infoziant: send the details o...
16  05/12/19   1:49 pm - AR❤: Sure mam. Soon I will share de...
17  05/12/19   2:00 pm - AR❤: I have read the Abstract mam. ...
18  05/12/19   2:04 pm - Mabel Infoziant: I think Vignesh ha...
19  05/12/19   2:04 pm - Mabel Infoziant: I have sent the ab...
20  05/12/19                              2:06 pm - AR❤: Ok mam
21  05/12/19   2:07 pm - AR❤: I have read both the abstract ...
22  05/12/19   4:44 pm - Mabel Infoziant: Yes we need to ya ...
23  05/12/19                           4:48 pm - AR❤: Sure mam.
24  05/12/19                   8:07 pm - AR❤: Shall I call mam?
25  08/12/19   10:45 pm - Mabel Infoziant: Hi I was at churc...
26  08/12/19                         11:52 pm - AR❤: It's k mam
27  08/12/19   11:55 pm - AR❤: Just to know the tomorrow pla...
28  09/12/19    12:09 pm - AR❤: Mam can u send Vignesh number??
29  09/12/19   12:13 pm - Mabel Infoziant: Vignesh ML Infozi...
30  09/12/19   12:23 pm - Mabel Infoziant: I was in a meetin...
31  09/12/19                    12:25 pm - AR❤: Can I cal u mam
32  09/12/19   12:26 pm - AR❤: Waiting for u r finalization ...
33  09/12/19   12:26 pm - AR❤: If we finiliaze I can work wi...
34  09/12/19   12:28 pm - AR❤: So what ever may be ..if you ...
35  09/12/19           12:28 pm - AR❤: You deleted this message
36  09/12/19                     12:29 pm - AR❤: Do the needful
37  09/12/19   12:41 pm - Mabel Infoziant: No ma please hold...
38  09/12/19                     12:42 pm - AR❤: Ok mam thank u
39  10/12/19   7:59 am - Mabel Infoziant: Ramisha we need to...
40  10/12/19   8:00 am - Mabel Infoziant: Be ready to discus...
41  10/12/19                            8:55 am - AR❤: Okay mam
42  12/12/19                      2:26 pm - Mabel Infoziant: ok
43  15/12/19                     8:22 pm - AR❤: Mam are u free?
44  15/12/19   8:40 pm - Mabel Infoziant: Am at church can c...
45  15/12/19   8:40 pm - AR❤: Kk mam. I will ask Arun brothe...
46  18/12/19                              3:09 pm - AR❤: Hi mam
47  18/12/19                    3:09 pm - AR❤: Any updates mam?
48  18/12/19   3:11 pm - Mabel Infoziant: U might have to st...
49  18/12/19   3:11 pm - Mabel Infoziant: There is one proje...
50  18/12/19                            3:12 pm - AR❤: Kk mam👍🏻

In [72]:
Message=df["Chat"].str.split("-",n=1,expand=True)
Message.head()

           0                                                 1
1   1:42 pm    Mabel Infoziant: Hi this is Mabel we just spoke
2   1:42 pm             Mabel Infoziant: What’s your full name
3   1:42 pm                                AR❤: Ramisha Rani K
4   1:42 pm                                Mabel Infoziant: Ok
5   1:42 pm            Mabel Infoziant: ramisharanik@gmail.com

In [73]:
df["Time"]=Message[0]
df.head()

       Date                                               Chat       Time
1  05/12/19   1:42 pm - Mabel Infoziant: Hi this is Mabel w...   1:42 pm
2  05/12/19   1:42 pm - Mabel Infoziant: What’s your full name   1:42 pm
3  05/12/19                      1:42 pm - AR❤: Ramisha Rani K   1:42 pm
4  05/12/19                      1:42 pm - Mabel Infoziant: Ok   1:42 pm
5  05/12/19   1:42 pm - Mabel Infoziant: ramisharanik@gmail...   1:42 pm

In [74]:
Message1=Message[1].str.split(":",n=1,expand=True)
Message1.head()

                  0                                1
1   Mabel Infoziant   Hi this is Mabel we just spoke
2   Mabel Infoziant            What’s your full name
3               AR❤                   Ramisha Rani K
4   Mabel Infoziant                               Ok
5   Mabel Infoziant           ramisharanik@gmail.com

In [75]:
df["name"]=Message1[0]
df.head()

,Date,Chat,Time,name
1,05/12/19,1:42 pm - Mabel Infoziant: Hi this is Mabel w...,1:42 pm,Mabel Infoziant
2,05/12/19,1:42 pm - Mabel Infoziant: What’s your full name,1:42 pm,Mabel Infoziant
3,05/12/19,1:42 pm - AR❤: Ramisha Rani K,1:42 pm,AR❤
4,05/12/19,1:42 pm - Mabel Infoziant: Ok,1:42 pm,Mabel Infoziant
5,05/12/19,1:42 pm - Mabel Infoziant: ramisharanik@gmail...,1:42 pm,Mabel Infoziant

In [76]:
df["Chat"]=Message1[1]
df.head()

       Date                             Chat       Time              name
1  05/12/19   Hi this is Mabel we just spoke   1:42 pm    Mabel Infoziant
2  05/12/19            What’s your full name   1:42 pm    Mabel Infoziant
3  05/12/19                   Ramisha Rani K   1:42 pm                AR❤
4  05/12/19                               Ok   1:42 pm    Mabel Infoziant
5  05/12/19           ramisharanik@gmail.com   1:42 pm    Mabel Infoziant

In [77]:
df=df[["Date","Time","name","Chat"]]
df.head()

       Date       Time              name                             Chat
1  05/12/19   1:42 pm    Mabel Infoziant   Hi this is Mabel we just spoke
2  05/12/19   1:42 pm    Mabel Infoziant            What’s your full name
3  05/12/19   1:42 pm                AR❤                   Ramisha Rani K
4  05/12/19   1:42 pm    Mabel Infoziant                               Ok
5  05/12/19   1:42 pm    Mabel Infoziant           ramisharanik@gmail.com

# SENTIMENT ANALYSIS

In [78]:
from nltk.sentiment.vader import SentimentIntensityAnalyzer

In [79]:
dataset=df

In [80]:
dataset.dropna(inplace=True)

In [81]:
import nltk
nltk.download('vader_lexicon')

[nltk_data] Downloading package vader_lexicon to
[nltk_data]     C:\Users\Anusuya\AppData\Roaming\nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

True

In [82]:
sid=SentimentIntensityAnalyzer()

In [83]:
senti=sid.polarity_scores(dataset['Chat'][4])

In [84]:
senti

{'neg': 0.0, 'neu': 0.0, 'pos': 1.0, 'compound': 0.296}

In [85]:
senti['compound']

0.296

In [86]:
dataset['Chat'][4]

' Ok'

In [87]:
def sentimentalAnalysis(data, columnname):
    import matplotlib.pyplot as plt
    import seaborn as sns
    "Importing Necessary Package"
    from nltk.sentiment.vader import SentimentIntensityAnalyzer
    sid=SentimentIntensityAnalyzer()

    "Deleting null or empty value"
    data.dropna(inplace=True)

    "Checking for a comment"

    "Creating respective columns"

    data['scores'] = data[columnname].apply(lambda commentText: sid.polarity_scores(commentText))
    data['compound']=data['scores'].apply(lambda score_dict:score_dict['compound'])
    data['Negative']=data['scores'].apply(lambda score_dict:score_dict['neg'])
    data['Positive']=data['scores'].apply(lambda score_dict:score_dict['pos'])
    data['Neutral']=data['scores'].apply(lambda score_dict:score_dict['neu'])

    "Creating final pos or neg using compound score"
    data['comp_score']=data['compound'].apply(lambda c: 'pos' if c>=0 else 'neg')
    plt.clf()
    "Checking how many post and neg"
    posneg=pd.DataFrame(data['comp_score'].value_counts())
    return posneg, data

In [88]:
pos,data_Senti=sentimentalAnalysis(dataset,columnname='Chat')

In [89]:
pos

            count
comp_score
pos            48
neg             2

# TOPIC MODELLING - NMF (Non-Negative Matrix Factorization)
It is an unsupervised machine learning technique used to discover hidden topics and patterns in text data.

# Goal: Automatically discover the main topics being discussed in the chats.

WhatsApp Chats
      ↓
TF-IDF
      ↓
Convert text → numbers
      ↓
NMF
      ↓
Find 5 hidden topics
      ↓
Show 10 important words for each topic

In [90]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [101]:
tfidf=TfidfVectorizer(max_df=0.95, min_df=2, stop_words='english')
dtm=tfidf.fit_transform(df["Chat"]) # dtm means Document-Term Matrix - A table containing the importance of words in each document/message.

In [100]:
from sklearn.decomposition import NMF #NMF means Non-Negative Matrix Factorization - to find hidden topics in your text.
nmf_model=NMF(n_components=5, random_state=42)
nmf_model.fit(dtm)

NMF(n_components=5, random_state=42)

In [102]:
for index, topic in enumerate (nmf_model.components_):
    results=([tfidf.get_feature_names_out()[i] for i in topic.argsort()[10:]]) # [10:] means take the last 10 items — the 10 highest-scoring words.
    print (results)

['just', 'church', 'abstracts', 'start', 'know', 'vignesh', 'number', 'details', 'think', 'hi', 'finiliaze', 'project', 'share', 'soon', 'ask', 'yes', 'sure', 'read', 'abstract', 'kk', 'yeah', 'mam']
['project', 'phone', 'yeah', 'number', 'office', 'ml', 'abstracts', 'ask', 'church', 'details', 'finiliaze', 'need', 'hi', 'kk', 'know', 'meeting', 'yes', 'just', 'send', 'tomorrow', 'mam', 'ok']
['church', 'sure', 'soon', 'kk', 'project', 'finiliaze', 'need', 'tomorrow', 'know', 'share', 'think', 'ml', 'details', 'abstracts', 'start', 'students', 'phone', 'ask', 'office', 'number', 'vignesh', 'send']
['ramisha', 'project', 'phone', 'ok', 'yeah', 'yes', 'need', 'ml', 'meeting', 'kk', 'finiliaze', 'details', 'ask', 'abstracts', 'number', 'mam', 'office', 'know', 'just', 'tomorrow', 'church', 'hi']
['kk', 'just', 'hi', 'finiliaze', 'vignesh', 'church', 'ask', 'abstracts', 'project', 'read', 'office', 'phone', 'students', 'know', 'sure', 'share', 'soon', 'meeting', 'details', 'yes', 'need', 'ramisha']

In [94]:
topic_results=nmf_model.transform(dtm)

In [96]:
df["Topic"]=topic_results.argmax(axis=1)

In [97]:
df["Topic"].value_counts()

Topic
0    22
2    12
4     6
3     5
1     5
Name: count, dtype: int64

# Inference:
First, TF-IDF converts the WhatsApp messages into numerical values based on word importance. 
Then NMF analyzes those values and tries to find 5 hidden topics. Finally, the code displays the 10 most important words associated with 
each topic, which we use to understand and name the topics.

# TOPIC MODELLING - LDA (Latent Dirichlet Allocation)
It is an unsupervised machine learning technique used for discovering hidden topics in text data.

In [103]:
from sklearn.decomposition import LatentDirichletAllocation

# Convert whatsapp chat text into word-count matrix
tfidf=TfidfVectorizer(max_df=0.95, min_df=2, stop_words='english')
dtm=tfidf.fit_transform(df["Chat"]) 

# LDA model
lda_model = LatentDirichletAllocation(n_components=5, random_state=42)

# Fit LDA model
lda_model.fit(dtm)

# Get all words
words = tfidf.get_feature_names_out()

# Display top 10 words for each topic
for index, topic in enumerate(lda_model.components_):
    top_words = [words[i] for i in topic.argsort()[-10:]]
    print("Topic", index + 1, ":", top_words)

Topic 1 : ['number', 'need', 'yes', 'hi', 'just', 'office', 'send', 'details', 'vignesh', 'ml']
Topic 2 : ['meeting', 'soon', 'ramisha', 'number', 'office', 'phone', 'students', 'yes', 'need', 'ok']
Topic 3 : ['ask', 'project', 'think', 'read', 'abstract', 'sure', 'kk', 'finiliaze', 'yeah', 'mam']
Topic 4 : ['soon', 'ask', 'mam', 'office', 'just', 'know', 'church', 'meeting', 'project', 'tomorrow']
Topic 5 : ['details', 'yes', 'ask', 'mam', 'send', 'church', 'ramisha', 'hi', 'start', 'abstracts']